kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: simple-chainsaw
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/techmaharaj/Testkube-vCluster-ArgoCD.git
  container:
    image: ghcr.io/kyverno/chainsaw:latest
  job:
    namespace: nginx
  steps:
  - name: Test ArgoCD deployment
    shell: |
      echo "Testing ArgoCD-deployed nginx with Chainsaw..."
      # Test the ArgoCD deployment in nginx namespace
      chainsaw test /data/repo/chainsaw-test/basic-test/chainsaw-test.yaml --namespace nginx
      echo "✅ ArgoCD deployment validated"
