apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: assert-argocd-deployment
spec:
  # Test in default namespace where ArgoCD deployed
  namespace: default
  steps:
    - try:
        - assert:
            file: assert-deployment.yaml
    - try:
        - script:
            content: |
              echo "Testing ArgoCD nginx deployment..."
              kubectl wait --for=condition=available deployment/nginx-deployment --timeout=60s
              echo "⚠️ Asserting in progress"
