apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: assert-argocd-deployment
spec:
  # Test in default namespace where ArgoCD deployed
  namespace: default
  steps:
    - try:
        - assert:
            file: assert-deployment.yaml
