name: Testkube on vCluster
on: push 

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
     
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Manually install gke-gcloud-auth-plugin
        run: |
          curl -fL -o gke-gcloud-auth-plugin https://dl.google.com/cloudsdk/credential-plugins/linux/amd64/gke-gcloud-auth-plugin
          chmod +x gke-gcloud-auth-plugin
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/
          file /usr/local/bin/gke-gcloud-auth-plugin

      - name: Set up GKE credentials and install auth plugin
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install vCluster CLI
        run: |
          curl -sSL https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64 -o vcluster
          chmod +x vcluster
          sudo mv vcluster /usr/local/bin
          
      - name: Connect to vCluster
        run: |
          kubectl get pods -A
          vcluster connect vcluster-testkube -n demo
          kubectl config current-context  # verify vcluster context is active
      
      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml

      - name: Configure Testkube
        run: |
          helm repo add kubeshop https://kubeshop.github.io/helm-charts ; helm repo update && helm upgrade --install --create-namespace testkube kubeshop/testkube --set testkube-api.cloud.key=${{ secrets.TESTKUBE_API_AGENT }} --set testkube-api.cloud.orgId=${{ secrets.TESTKUBE_ORG_ID }} --set testkube-api.cloud.envId=${{ secrets.TESTKUBE_ENV_ID }} --set testkube-api.minio.enabled=false --set mongodb.enabled=false --set testkube-dashboard.enabled=false --set testkube-api.cloud.url=agent.testkube.io:443 --namespace testkube

      - name: Verify installation
        run: helm list -n testkube
  
      - name: Check Pods Status
        run: |
          kubectl get pods --all-namespaces -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          sleep 100

      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1        
      - run: |
          kubectl apply -f tw.yaml
          testkube run tw curl-vcluster-app -f --config url=http://nginx-service.default.svc.cluster.local
