name: Testkube on vCluster
on:
  pull_request:
    branches:
      - main 

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
     
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Manually install auth plugin
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg curl
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
 
      - name: Set up GKE credentials and install auth plugin
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install vCluster CLI
        run: |
          curl -sSL https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64 -o vcluster
          chmod +x vcluster
          sudo mv vcluster /usr/local/bin

      - name: Create vCluster
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "Running for PR #$PR_NUMBER"
          vcluster create testkube-vcluster-$PR_NUMBER --namespace demo --connect=false
          echo "Waiting for vCluster to be ready..."
          sleep 100

      - name: Connect to vCluster
        run: |
          PR_NUMBER=${{ github.event.number }}
          vcluster connect testkube-vcluster-$PR_NUMBER --namespace demo
          kubectl config current-context  # verify vcluster context is active
          echo "Show pods on vCluster"
          kubectl get pods -n demo
      
      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml
          kubectl get all

      - name: Configure Testkube
        run: |
          helm repo add kubeshop https://kubeshop.github.io/helm-charts ; helm repo update && helm upgrade --install --create-namespace testkube kubeshop/testkube --set testkube-api.cloud.key=${{ secrets.TESTKUBE_API_AGENT }} --set testkube-api.cloud.orgId=${{ secrets.TESTKUBE_ORG_ID }} --set testkube-api.cloud.envId=${{ secrets.TESTKUBE_ENV_ID }} --set testkube-api.minio.enabled=false --set mongodb.enabled=false --set testkube-dashboard.enabled=false --set testkube-api.cloud.url=agent.testkube.io:443 --namespace testkube

      - name: Verify installation
        run: helm list -n testkube
  
      - name: Check Pods Status
        run: |
          kubectl get pods --all-namespaces -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          sleep 100

      - name: Run Test with Testkube
        run: |
          kubectl apply -f tw.yaml
          testkube run tw curl-nginx-app -f --config url=http://nginx-service.default.svc.cluster.local
          sleep 100

      - name: Check Test Execution Status
        run: |
          testkube get testworkflow curl-nginx-app

      - name: Delete vCluster
        run: |
          PR_NUMBER=${{ github.event.number }}
          vcluster delete testkube-vcluster-$PR_NUMBER --namespace demo
